site_name: SUVTools
repo_url: https://pranabdas.github.io/
site_description: Python libraries to read, analyze, and visualize SUV beamline
data.
site_author: Pranab Das

nav:
    - Table of Contents: index.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list
