[tool.poetry]
name = "suvtools"
version = "1.0.2"
description = "Python library for analyzing and visualizing SSLS SUV Beamline data."
authors = ["Pranab Das"]
license = "MIT"
readme = "README.md"
homepage = "https://pranabdas.github.io/suvtools/"
repository = "https://github.com/pranabdas/suvtools"
documentation = "https://pranabdas.github.io/suvtools/docs/"
keywords = [
    "python", "data-analysis", "matplotlib", "materials-science",
    "condensed-matter-physics"]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.9.2"
numpy = "^2.0.2"
pandas = "^2.2.3"
scipy = "^1.13.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"
jupyterlab = "^4.2.5"

[tool.poetry.group.tests.dependencies]
psutil = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
