[tool.poetry]
name = "suvtools"
version = "1.0.0"
description = "Python library for analyzing and visualizing SSLS SUV Beamline data."
authors = ["Pranab Das"]
license = "MIT"
readme = "README.md"
homepage = "https://pranabdas.github.io/suvtools/"
repository = "https://github.com/pranabdas/suvtools"
documentation = "https://pranabdas.github.io/suvtools/docs/"
keywords = [
    "python", "data-analysis", "matplotlib", "materials-science",
    "surface-science", "condensed-matter-physics", "photoelectron-spectroscopy",
    "arpes"]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.7.5"
numpy = "^1.24.4"
pandas = "^2.0.3"
scipy = "^1.9.3"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.3.1"
jupyterlab = "^4.2.5"

[tool.poetry.group.tests.dependencies]
psutil = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
