name: Python tests
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/python-tests.yml
      - dataset/**
      - poetry.lock
      - pyproject.toml
      - src/suvtools/**
      - tests/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/python-tests.yml
      - dataset/**
      - poetry.lock
      - pyproject.toml
      - src/suvtools/**
      - tests/**

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14.0-rc.3"

    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install

      - name: Run unittest
        run: poetry run python -m unittest discover tests
